- name: variables
  hosts: web
  vars:
    COURSE: ansible
    TARINER: PERAIAH
    DURATION: 10HRS

  tasks:
  - name: print the data
    ansible.builtin.debug:
      msg: "the course is: {{$COURSE}}, tariner: {{$TARINER}}, duration: {{$DURATION}}"