- name: data types
  hosts: local 
  connection: local
  vars:
    cousre: "linux"
    is_live: true
    duration: 10hr

    tools:
    - unix
    - os 
    - rpm

    services:
      cloud: aws
      so: kernel
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "the couse is: {{ course }}, is_live?: {{ is_live }}, Duration: {{ duration }}, Tools are: {{ tools }}, Services are: {{ services }},"
