- name: conditions in variables
  hosts: local
  connection: local
  vars:
    number: 4
  tasks:
  - name: check number is less than 10 or not
    ansible.builtin.debud:
      msg: the given number {{ number }} is less than 10"
      