- name: functions
  hosts: local
  connection: local
  vars:
    technologies: linux, python, aws, devops, cloud #string
    trainer: "peraiah tellagorla"
    gmail: tellagorla26@gmail.com
    ipaddress: "192.168.3.3"

    tags:
      Application: payment
      Environment: dev

    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev

  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "hello, {{ trainer | default('naresh') }}"
  
  - name: string into list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert uppercase
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

