- name: functions
  hosts: local
  connection: local
  vars:
    technologies: linux, python, aws, devops, cloud
    trainer: "peraiah tellagorla"
    gmail: tellagorla26@gmail.com
    ipaddress: "192.168.3.3"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "hello, {{ name | default('naresh') }}"
