- name: loops in ansible
  hosts: local
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.debug:
      msg: "hello {{ item }}"
      loop:
      - peraiah
      - ganesh
      - rambabu
      - gopi